return {
  -- price_ema = , - емы
  { internalName = "GraviSuite:vajra", displayName = "Ваджра", price = 441.05, price_ema = 13, currency = "res" },
  { internalName = "dwcity:Powder11", displayName = "Трижды сжатый камень", price = 10.39, price_ema = 0.1, currency = "res" },
  { internalName = "dwcity:Powder7", displayName = "Дважды сжатый адский кирпич", price = 0.66, currency = "res" },
  { internalName = "minecraft:cauldron", displayName = "Котёл", price = 0.7, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ плотный кабель - Изменчивый", price = 0.41, currency = "res", damage = 76 },
  { internalName = "ae2stuff:Cable", displayName = "МЭ улучшенный кабель - Изменчивый", price = 2.17, currency = "res", damage = 16 },
  { internalName = "Forestry:craftingMaterial", displayName = "Пропитанная обшивка", price = 2.97, currency = "res", damage = 6 },
  { internalName = "Forestry:oakStick", displayName = "Полированная палка", price = 0.60, currency = "res" },
  { internalName = "metadrive:block_compressor", displayName = "Квантовый компрессор", price = 108.60, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_thermal_smelter", displayName = "Квантовая индукционная плавильня", price = 1100.79, price_ema = 21, currency = "res" },
  { internalName = "metadrive:block_advanced_squeezer", displayName = "Квантовая соковыжималка", price = 119.72, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_ic2_centrifuge", displayName = "Квантовая термальная центрифуга", price = 119.72, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_advanced_carpenter", displayName = "Квантовый плотник", price = 119.72, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_extractor", displayName = "Квантовый экстрактор", price = 108.61, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_ore_washing", displayName = "Квантовый рудопромывочный механизм", price = 113.37, price_ema = 3, currency = "res" },
  { internalName = "metadrive:block_lava_generator", displayName = "Квантовый производитель лавы", price = 122.49, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_macverator", displayName = "Квантовый дробитель", price = 108.60, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_furnace", displayName = "Квантовая печь", price = 108.34, price_ema = 2, currency = "res" },
  { internalName = "metadrive:block_metal_former", displayName = "Квантовый металлоформовочный механизм", price = 110.21, price_ema = 2, currency = "res" },
  { internalName = "Forestry:propolis", displayName = "Прополис", price = 0.1, currency = "res" },
  { internalName = "minecraft:leather", displayName = "Кожа", price = 0.1, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockController", displayName = "МЭ контроллер", price = 1.21, currency = "res" },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 0.27, currency = "res", damage = 2 },
  { internalName = "EnderIO:itemLiquidConduit", displayName = "Жидкостная труба из мелодичного сплава", price = 0.12, currency = "res", damage = 5 },
  { internalName = "dwcity:Nano_seal2", displayName = "Тусклая нано-печать", price = 588.30, currency = "res" },
  { internalName = "dwcity:Dragon_seal2", displayName = "Тусклая печать дракона", price = 1000.50, price_ema = 60, currency = "res" },
  { internalName = "dwcity:Lamp_seal2", displayName = "Тусклая печать света", price = 2.44, currency = "res" },
  { internalName = "dwcity:Bee_seal2", displayName = "Тусклая пчелиная печать", price = 79.33, price_ema = 2, currency = "res" },
  { internalName = "dwcity:Liquid_seal2", displayName = "Тусклая жидкостная печать", price = 6.66, currency = "res" },
  { internalName = "dwcity:Cube_seal2", displayName = "Тусклая кубическая печать", price = 56.41, currency = "res" },
  { internalName = "dwcity:Machine_seal2", displayName = "Тусклая механическая печать", price = 33.32, currency = "res" },
  { internalName = "dwcity:Optic_seal2", displayName = "Тусклая оптическая печать", price = 124.53, currency = "res" },
  { internalName = "dwcity:Chest_seal22", displayName = "Тусклая печать безопастности", price = 34.03, currency = "res" },
  { internalName = "dwcity:Food_seal2", displayName = "Тусклая печать голода", price = 5.82, currency = "res" },
  { internalName = "dwcity:Dnk_seal2", displayName = "Тусклая печать ДНК", price = 149.46, price_ema = 10, currency = "res" },
  { internalName = "dwcity:Sword_seal2", displayName = "Тусклая печать обороны", price = 12.35, currency = "res" },
  { internalName = "dwcity:Flower_seal2", displayName = "Тусклая печать розы", price = 0.15, currency = "res" },
  { internalName = "dwcity:Death_seal2", displayName = "Тусклая печать смерти", price = 93.67, currency = "res" },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 0.27, currency = "res", damage = 2 },
  { internalName = "metadrive:block_ic2_1_solar_panel", displayName = "Индустриальная солнечная панель II уровня", price = 17.44, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ жидкостный компонент хранилища", price = 214.51, currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ компонент хранилища", price = 195.85, currency = "res", damage = 9 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "16K МЭ компонент хранения", price = 10.86, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.16k", displayName = "16K МЭ ячейка хранения", price = 6.94, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "16K хранилище создания", price = 7.26, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "16K МЭ жидкостный компонент хранилища", price = 7.65, currency = "res", damage = 6 },
  { internalName = "dwcity:Chip_16bit", displayName = "16-битный чип", price = 2.37, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "1K МЭ компонент хранения", price = 0.48, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.1k", displayName = "1K МЭ ячейка хранения", price = 0.94, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "1K хранилище создания", price = 1.25, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1K МЭ жидкостный компонент хранилища", price = 0.78, currency = "res", damage = 4 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ жидкостный компонент хранилища", price = 71.27, currency = "res", damage = 8 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ компонент хранилища", price = 64.73, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "4K МЭ компонент хранения", price = 1.64, currency = "res", damage = 36 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.4k", displayName = "4K МЭ ячейка хранения", price = 2.1, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "4K хранилище создания", price = 2.41, currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "4K МЭ жидкостный компонент хранилища", price = 2.48, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "64K МЭ компонент хранения", price = 21.02, currency = "res", damage = 38 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.64k", displayName = "64K МЭ ячейка хранения", price = 21.48, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "64K хранилище создания", price = 21.8, currency = "res", damage = 3 },
  { internalName = "extracells:storage.component", displayName = "64K МЭ жидкостный компонент хранилища", price = 23.54, currency = "res", damage = 7 },
  { internalName = "dwcity:Chip_64bit", displayName = "64-битный чип", price = 13.62, currency = "res" },
  { internalName = "EnderIO:blockSliceAndSplice", displayName = "Отрубатель и сращиватель", price = 2.37, currency = "res" },
  { internalName = "minecraft:nether_wart", displayName = "Адский нарост", price = 0.15, currency = "res" },
  { internalName = "dwcity:Akvamarin", displayName = "Аквамарин", price = 8.89, currency = "res" },
  { internalName = "Genetics:labMachine", displayName = "Акклиматизатор", price = 3.38, currency = "res" },
  { internalName = "IC2:itemArmorBatpack", displayName = "Аккумуляторный ранец", price = 1.99, currency = "res" },
  { internalName = "IC2:itemToolDDrill", displayName = "Алмазный бур", price = 8.92, currency = "res" },
  { internalName = "IronChest:BlockIronChest", displayName = "Алмазный сундук", price = 3.1, currency = "res" },
  { internalName = "IC2:itemCropnalyzer", displayName = "Анализатор агрокультур", price = 0.70, currency = "res" },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Армированная железная пластина", price = 0.49, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Базовая карта", price = 0.33, currency = "res", damage = 25 },
  { internalName = "dwcity:Basic_plan", displayName = "Базовый чертёж", price = 2.05, currency = "res" },
  { internalName = "BinnieCore:containerCylinder", displayName = "Баллон сырой ДНК", price = 100, price_ema = 3, currency = "res" },
  { internalName = "ae2wct:infinityBoosterCard", displayName = "Бесконечная карта усиления", price = 1470.00, price_ema = 30, currency = "res" },
  { internalName = "ectracells:terminal.fluid.wireless", displayName = "Беспроводной МЭ жидкостный терминал", price = 7.65, currency = "res" },
  { internalName = "extracells:terminal.universal.wireless", displayName = "Беспроводной МЭ универсальный терминал", price = 2000.00, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Беспроводной приёмник", price = 1.23, currency = "res" },
  { internalName = "appliedenergistics2:item.ToolWirelessTeminal", displayName = "Беспроводной терминал", price = 7.35, currency = "res" },
  { internalName = "ae2wct:wirelessCraftingTerminal", displayName = "Беспроводной терминал создания", price = 236.41, currency = "res" },
  { internalName = "appliedenergistics2:item.ToolBiometricCard", displayName = "Биометрическая карта", price = 0.99, currency = "res" },
  { internalName = "IC2:blockMetal", displayName = "Блок закалённого железа", price = 1.44, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок обработки создания", price = 1.3, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок создания", price = 0.78, currency = "res" },
  { internalName = "ThermalExpansion:material", displayName = "Богатое удобрение", price = 0.4, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Ботинки Виверны", price = 567.13, currency = "res" },
  { internalName = "IC2:itemIngot", displayName = "Бронзовый слиток", price = 0.1, currency = "res", damage = 2 },
  { internalName = "minecraft:cobblestone", displayName = "Булыжник", price = 0.4, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый порошок", price = 0.4, currency = "res", damage = 1025 },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый стержень", price = 0.16, currency = "res", damage = 1024 },
  { internalName = "minecraft:bucket", displayName = "Ведро", price = 0.3, currency = "res" },
  { internalName = "minecraft:crafting_table", displayName = "Верстак", price = 0.1, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCellWorkbench", displayName = "Верстак для ячеек", price = 0.59, currency = "res" },
  { internalName = "EnderIO:itemMaterial", displayName = "Вибрирующий кристалл", price = 1.65, currency = "res", damage = 6 },
  { internalName = "EnderIO:itemAlloy", displayName = "Вибрирующий сплав", price = 0.73, currency = "res", damage = 2 },
  { internalName = "minecraft:hopper", displayName = "Воронка", price = 0.5, currency = "res" },
  { internalName = "ppliedenergistics2:tile.BlockInscriber", displayName = "Высекатель", price = 0.85, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Логический процессор", price = 0.15, currency = "res", damage = 22 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Вычислительный процессор", price = 0.83, currency = "res", damage = 23 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Инженерный процессор", price = 0.52, currency = "res", damage = 24 },
  { internalName = "IC2:blockGenerator", displayName = "Генератор", price = 1.07, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Генератор биотоплива", price = 1.88, currency = "res", damage = 11 },
  { internalName = "IC2:blockGenerator", displayName = "Геотермальный генератор", price = 1.24, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockEndermanSkull", displayName = "Голова стража Края", price = 2.2, currency = "res" },
  { internalName = "minecraft:gravel", displayName = "Гравий", price = 0.67, currency = "res" },
  { internalName = "minecraft:dirt", displayName = "Земля", price = 0.4, currency = "res" },
  { internalName = "DraconicEvolution:draconium", displayName = "Дракониевый блок", price = 26.83, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Дракониевый слиток", price = 2.98, currency = "res" },
  { internalName = "DraconicEvolution:draconicSword", displayName = "Драконий меч", price = 6000.64, price_ema = 188, currency = "res" },
  { internalName = "DraconicEvolution:draconicPickaxe", displayName = "Драконья кирка", price = 6000.72, price_ema = 227, currency = "res" },
  { internalName = "DraconicEvolution:draconicAxe", displayName = "Драконий топор", price = 6000.72, price_ema = 227, currency = "res" },
  { internalName = "DraconicEvolution:draconicShovel", displayName = "Драконья лопата", price = 6000.72, price_ema = 227, currency = "res" },
  { internalName = "DraconicEvolution:draconicBow", displayName = "Драконий лук", price = 6000.91, price_ema = 182, currency = "res" },
  { internalName = "DraconicEvolution:draconicHelm", displayName = "Драконий шлем", price = 6000.01, price_ema = 128, currency = "res" },
  { internalName = "DraconicEvolution:draconicChest", displayName = "Драконий нагрудник", price = 8000.8, price_ema = 333, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Драконьи поножи", price = 6000.86, price_ema = 120, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Драконьи ботинки", price = 6000.22, price_ema = 118, currency = "res" },
  { internalName = "DraconicEvolution:draconicStaffOfPower", displayName = "Драконий посох силы", price = 30000.51, price_ema = 3874, currency = "res" },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Драконье ядро", price = 15.09, currency = "res" },
  { internalName = "dwcity:Granat", displayName = "Гранат", price = 4.56, currency = "res" },
  { internalName = "minecraft:red_mushroom", displayName = "Гриб", price = 0.1, currency = "res" },
  { internalName = "Botany:pigment", displayName = "Зелёный краситель", price = 0.11, currency = "res", damage = 13 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал", price = 1.14, currency = "res", damage = 380 },
  { internalName = "appliedenergistics2:item.ItemBlockSecurity", displayName = "МЭ терминал безопасности", price = 0.68, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал интерфейсов", price = 1.46, currency = "res", damage = 480 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал создания", price = 0.76, currency = "res", damage = 360 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал шаблонов", price = 1.28, currency = "res", damage = 340 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ умный кабель - Изменчивый", price = 0.3, currency = "res", damage = 56 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина импорта", price = 0.48, currency = "res", damage = 240 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина экспорта", price = 0.47, currency = "res", damage = 260 },
  { internalName = "IC2:itemPlates", displayName = "Медная пластина", price = 0.1, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Медная электронная лампа", price = 0.65, currency = "res" },
  { internalName = "IC2:itemCable", displayName = "Медный провод", price = 0.33, currency = "res", damage = 1 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Мелодичный конденсатор", price = 85.70, price_ema = 5, currency = "res", damage = 4 },
  { internalName = "IC2:blockMachine2", displayName = "Металлоформовочный механизм", price = 2.75, currency = "res", damage = 4 },
  { internalName = "dwcity:Machine_seal2", displayName = "Механическая печать", price = 36.66, currency = "res" },
  { internalName = "DraconicEvolution:wyvernSword", displayName = "Меч Виверны", price = 400.82, price_ema = 14, currency = "res" },
  { internalName = "metadrive:module_fortune_luck_changer_tier_3", displayName = "Модуль удачи IV", price = 2500.0, currency = "res" },
  { internalName = "dwcity:Module_seal", displayName = "Модульная печать", price = 10.5, currency = "res" },
  { internalName = "metadrive:block_molecular_transfirmer", displayName = "Молекулярный преобразователь", price = 47.7, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockMolecularAssembler", displayName = "Молекулярный сборщик", price = 0.78, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingMonitor", displayName = "Монитор создания", price = 1.14, currency = "res" },
  { internalName = "minecraft:carrot", displayName = "Морковь", price = 0.1, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Мутатор улья", price = 9.32, currency = "res" },
  { internalName = "IC2NuclearControl:ItemMultipleSensorKit", displayName = "Набор для счётчика энергии", price = 0.73, currency = "res" },
  { internalName = "IC2NuclearControl:ItemEnergySensorKit", displayName = "Набор для энергетического хранилища", price = 0.41, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Навес улья", price = 8.16, currency = "res", damage = 2 },
  { internalName = "DraconicEvolution:wyvernChest", displayName = "Нагрудник Виверны", price = 700.23, price_ema = 30, currency = "res" },
  { internalName = "IC2:itemArmorNanoBoots", displayName = "Нано-ботинки", price = 6.24, currency = "res" },
  { internalName = "IC2:itemArmorNanoChestplate", displayName = "Нано-кираса", price = 7.69, currency = "res" },
  { internalName = "IC2:itemArmorLegas", displayName = "Нано-поножи", price = 7.26, currency = "res" },
  { internalName = "IC2:itemNanoSaber", displayName = "Нано-сабля", price = 8.1, currency = "res" },
  { internalName = "IC2:itemArmorNanoHelmet", displayName = "Нано-шлем", price = 14.3, currency = "res" },
  { internalName = "ThermalExpansion:Cell", displayName = "Наполнитель энергии", price = 61.96, currency = "res" },
  { internalName = "EnderIO:itemAlloy", displayName = "Наэлектризованная сталь", price = 0.13, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockSkyStone", displayName = "Небесный камень", price = 0.13, currency = "res" },
  { internalName = "IC2:itemBatREDischarged", displayName = "Незаряженный аккумулятор", price = 0.27, currency = "res" },
  { internalName = "Forestry:alveary", displayName = "Обогреватель улья", price = 8.27, currency = "res", damage = 4 },
  { internalName = "minecraft:obsidian", displayName = "Обсидиан", price = 0.5, currency = "res" },
  { internalName = "IC2:itemPlates", displayName = "Обсидиановая пластина", price = 0.13, currency = "res", damage = 7 },
  { internalName = "IC2:itemDust", displayName = "Обсидиановая пыль", price = 0.13, currency = "res", damage = 11 },    
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Объединитель солнечных панелей", price = 58.39, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Огненная электронная лампа", price = 0.72, currency = "res", damage = 7 },
  { internalName = "minecraft:ender_eye", displayName = "Око Эндера", price = 0.38, currency = "res" },
  { internalName = "ThermalFoundation:tool.fishingRodTin", displayName = "Оловянная пластина", price = 0.1, currency = "res", damage = 1 },
  { internalName = "Botany:insulatedTube", displayName = "Оловянная электронная лампа", price = 0.65, currency = "res", damage = 1 },
  { internalName = "dwcity:Optic_seal2", displayName = "Оптическая печать", price = 127.86, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Осветитель улья", price = 9.22, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Основной конденсатор", price = 0.64, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Основной корпус механизма", price = 0.8, currency = "res" },
  { internalName = "EnderIO:itemBasicFilterUpgrade", displayName = "Основной предметный фильтр", price = 0.54, currency = "res" },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная лазуритовая пластина", price = 0.15, currency = "res", damage = 8 },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная обсидиановая пластина", price = 0.11, currency = "res", damage = 7 },
  { internalName = "dwcity:Enderium_plate2", displayName = "Плотная эндериумная пластина", price = 8.01, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockDenseEnergyCell", displayName = "Плотная энергетическая ячейка", price = 5.44, currency = "res" },
  { internalName = "Forestry:factory", displayName = "Плотник", price = 1.4, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockPainter", displayName = "Покрасочный механизм", price = 2.42, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Поножи Виверны", price = 560.77, price_ema = 9,currency = "res" },
  { internalName = "minecraft:gunpowder", displayName = "Порох", price = 0.5, currency = "res" },
  { internalName = "minecraft:piston", displayName = "Поршень", price = 0.12, currency = "res" },
  { internalName = "EnderIO:itemTravelStaff", displayName = "Посох путешествия", price = 1.36, currency = "res" },
  { internalName = "EnderIO:itemConduit", displayName = "Предметная труба", price = 0.18, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyAcceptor", displayName = "Приёмщик энергии", price = 0.65, currency = "res" },
  { internalName = "DraconicEvolution:awakenedCore", displayName = "Пробуждённое ядро", price = 1400.01, price_ema = 13, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Пробуждённый дракониевый слиток", price = 70.83, price_ema = 4, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Продвинутая карта", price = 0.7, currency = "res", damage = 28 },
  { internalName = "Forestry:chipsets", displayName = "Продвинутая печатная плата", price = 0.42, currency = "res", damage = 1 },
  { internalName = "IC2:itemPartCircuiAdv", displayName = "Продвинутая электросхема", price = 0.96, currency = "res" },
  { internalName = "IC2:itemArmorAdvBatpack", displayName = "Продвинутый аккумуляторный ранец", price = 5.14, currency = "res" },
  { internalName = "ae2stuff:Inscriber", displayName = "Продвинутый высекатель", price = 52.56, price_ema = 3, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Продвинутый корпус механизма", price = 2.82, currency = "res", damage = 12 },
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Продвинутый объединитель солнечных панелей", price = 900.35, price_ema = 80, currency = "res", damage = 1 },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Производитель лавы", price = 2.18, currency = "res", damage = 5 },
  { internalName = "Forestry:frameImpregnated", displayName = "Пропитанная рамка", price = 0.17, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Прорезиненная электронная лампа", price = 0.62, currency = "res", damage = 8 },
  { internalName = "EnderIO:blockTransceiver", displayName = "Пространственный приёмопередатчик", price = 8.9, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (1-ый уровень)", price = 1.16, currency = "res", damage = 8 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (2-ой уровень)", price = 1.53, currency = "res", damage = 9 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (3-ий уровень)", price = 6.15, currency = "res", damage = 10 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (2-ой уровень)", price = 14.72, currency = "res", damage = 102 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (Творческий)", price = 414.14, price_ema = 30, currency = "res", damage = 103 },
  { internalName = "EnderIO:itemAlloy", displayName = "Пульсирующее железо", price = 0.43, currency = "res", damage = 5 },
  { internalName = "minecraft:glass_bottle", displayName = "Пустая капсула", price = 0.33, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пустой шаблон", price = 1.21, currency = "res",  damage = 52 },
  { internalName = "dwcity:Bee_seal2", displayName = "Пчелиная печать", price = 84.66, currency = "res" },
  { internalName = "Forestry:beeswax", displayName = "Пчелиный воск", price = 0.1, currency = "res" },
  { internalName = "Forestry:alveary", displayName = "Пчелиный улей", price = 7.0, price_ema = 0.8, currency = "res" },
  { internalName = "minecraft:wheat", displayName = "Пшеница", price = 0.15, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Пыль криотеума", price = 0.35, currency = "res", damage = 513 },
  { internalName = "ThermalFoundation:material", displayName = "Пыль пиротеума", price = 0.63, currency = "res", damage = 512 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пыль небесного камня", price = 0.13, currency = "res",  damage = 45 },
  { internalName = "IC2:reactorVentGold", displayName = "Разогнанный теплоотвод", price = 2.78, currency = "res" },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Основная)", price = 0.9, currency = "res" },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Резонирующая)", price = 7.99, currency = "res", damage = 3 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Укреплённая)", price = 3.53, currency = "res", damage = 2 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Усиленная)", price = 2.08, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка свинцовой энергетической ячейки", price = 0.68, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка тессаракта (Полная)", price = 5.74, currency = "res", damage = 11 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная отдающая катушка", price = 0.68, currency = "res", damage = 80 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная принимающая катушка", price = 0.61, currency = "res", damage = 128 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичное сито", price = 0.4, currency = "res", damage = 112 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вулканический катализатор", price = 0.67, currency = "res", damage = 313 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная воронка", price = 0.26, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная красная схема", price = 0.64, currency = "res", damage = 32 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная модульная структура", price = 0.17, currency = "res", damage = 16 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированный сервомеханизм", price = 0.26, currency = "res" },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Камера аннулирования", price = 0.96, currency = "res", damage = 144 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Канал отдающей катушки", price = 0.16, currency = "res", damage = 48 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ограничитель поля намагничивания", price = 0.26, currency = "res", damage = 49 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Оптимизация флаксовой связи", price = 1.35, currency = "res", damage = 65 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Отклик гиросервомеханизма", price = 1.14, currency = "res", damage = 114 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пирокластическое генерирование", price = 0.74, currency = "res", damage = 314 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пространственно-временной унификатор", price = 1.46, currency = "res", damage = 130 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Разогнанный модульный редуктор", price = 0.78, currency = "res", damage = 129 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Регулятор криогенной катушки", price = 1.46, currency = "res", damage = 66 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Стабилизированная рамка", price = 0.88, currency = "res", damage = 113 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Тривекционная камера", price = 0.69, currency = "res", damage = 256 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Усилитель модуляции флакса", price = 1.38, currency = "res", damage = 81 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ускоренная экструзия", price = 0.62, currency = "res", damage = 312 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Флаксовый усилитель криогенной катушки", price = 1.61, currency = "res", damage = 82 },
  { internalName = "IC2:blockReactorChamber", displayName = "Реакторная камера", price = 11.2, currency = "res" },
  { internalName = "IC2:reactorPlating", displayName = "Реакторная обшивка", price = 0.58, currency = "res" },
  { internalName = "IC2:blockreactorvessel", displayName = "Реакторный корпус", price = 0.16, currency = "res" },
  { internalName = "IC2:blockReactorAccessHatch", displayName = "Реакторный люк", price = 1.1, currency = "res" },
  { internalName = "IC2:blockReactorFluidPort", displayName = "Реакторный насос", price = 1.25, currency = "res" },
  { internalName = "IC2:blockReactorRedstonePort", displayName = "Реакторный проводник красного сигнала", price = 1.27, currency = "res" },
  { internalName = "IC2:reactorVentCore", displayName = "Реакторный теплоотвод", price = 2.28, currency = "res" },
  { internalName = "EnderIO:blockReservoir", displayName = "Резервуар", price = 0.2, currency = "res" },
  { internalName = "IC2:itemRubber", displayName = "Резина", price = 0.5, currency = "res" },
  { internalName = "ThermalExpansion:Workbench", displayName = "Резонирующий вулканический пресс", price = 9.35, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Tank", displayName = "Резонирующий переносной бак", price = 60.71, price_ema = 4, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Strongbox", displayName = "Резонирующий сейф", price = 4.74, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:capacitor", displayName = "Резонирующий флаксовый конденсатор", price = 3.6, currency = "res", damage = 5 },
  { internalName = "IC2:blockMachine2", displayName = "Рудопромывочный механизм", price = 3.91, currency = "res", damage = 5 },
  { internalName = "dwcity:Sostav", displayName = "Рыбий жир", price = 0.9, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Рыболов", price = 2.92, currency = "res", damage = 1 },
  { internalName = "minecraft:lever", displayName = "Рычаг", price = 0.17, currency = "res" },
  { internalName = "MineFactoryReloaded:rubberwood.sapling", displayName = "Саженец гевеи", price = 0.11, currency = "res" },
  { internalName = "EnderIO:itemMaterial", displayName = "Самородок вибрирующего сплава", price = 0.81, currency = "res", damage = 4 },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Саннариум", price = 3.58, price_ema = 0.2 , currency = "res" },
  { internalName = "minecraft:sugar", displayName = "Сахар", price = 0.5, currency = "res" },
  { internalName = "minecraft:reeds", displayName = "Сахарный тростник", price = 0.1, currency = "res" },
  { internalName = "IC2:blockMachine3", displayName = "Сборщик урожая", price = 25.21, currency = "res", damage = 7 },
  { internalName = "IC2:itemPlates", displayName = "Свинцовая пластина", price = 0.12, currency = "res", damage = 6 },
  { internalName = "EnderIO:blockSoulBinder", displayName = "Связыватель душ", price = 10.56, currency = "res" },
  { internalName = "IC2:reactorUraniumDual", displayName = "Сдвоенный топливный стержень (Уран)", price = 0.98, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Селитра", price = 0.1, currency = "res", damage = 17 },
  { internalName = "minecraft:wheat_seeds", displayName = "Семена пшеницы", price = 0.1, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Сера", price = 0.25, currency = "res", damage = 16 },
  { internalName = "OpenComputers:item", displayName = "Сетевая карта", price = 0.27, currency = "res", damage = 11 },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Сеятель", price = 2.34, currency = "res" },
  { internalName = "IC2:itemRecipePart", displayName = "Силовой агрегат", price = 2.26, currency = "res", damage = 2 },
  { internalName = "PowerUtils:BlockMain", displayName = "Силовой конвертер", price = 13.68, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Синаловый слиток", price = 0.25, currency = "res", damage = 74 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Сингулярность", price = 5.5, currency = "res", damage = 47 },
  { internalName = "Forestry:alveary", displayName = "Сито улья", price = 9.45, currency = "res", damage = 7 },
  { internalName = "IC2:blockMetal:3", displayName = "Слиток закалённого железа", price = 0.16, currency = "res", damage = 3 },
  { internalName = "IC2:itemIngot", displayName = "Слиток урана", price = 0.25, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Слиток эндериума", price = 0.89, currency = "res", damage = 76 },
  { internalName = "ThermalFoundation:material", displayName = "Смесь эндериума", price = 0.86, currency = "res", damage = 44 },
  { internalName = "minecraft:snowball", displayName = "Снежок", price = 0.1, currency = "res" },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Снижение скорости для предметной трубы", price = 1.07, currency = "res", damage = 1 },
  { internalName = "luxinfineitems:AECompressedSpeedCard", displayName = "Совершенная карта ускорения", price = 17.79, currency = "res", damage = 2 },
  { internalName = "luxinfineitems:advanced_portable_storage_cell_2", displayName = "Совершенная переносная ячейка", price = 180.13, price_ema = 10, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Совершенный молекулярный сборщик", price = 5.78, currency = "res", damage = 1 },
  { internalName = "OpenConputers:item", displayName = "Соединённая карта", price = 3.85, currency = "res", damage = 51 },
  { internalName = "Forestry:factory", displayName = "Соковыжималка", price = 1.4, currency = "res", damage = 5 },
  { internalName = "IC2:blockGenerator", displayName = "Солнечная панель", price = 2.13, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine3", displayName = "Солнечный опреснитель", price = 1.2, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemAlloy", displayName = "Сплав из красного камня", price = 0.2, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine2", displayName = "Термальная центрифуга", price = 16.35, currency = "res", damage = 3 },
  { internalName = "dwcity:Topaz", displayName = "Топаз", price = 1.12, currency = "res" },
  { internalName = "IC2:itemTritiumCell", displayName = "Топливный стержень (Тритий)", price = 1.5, currency = "res" },
  { internalName = "IC2:reactoryUraniumSimple", displayName = "Топливный стержень (Уран)", price = 0.44, currency = "res" },
  { internalName = "IC2:blockPersonal", displayName = "Торговый аппарат", price = 29.9, currency = "res", damage = 1 },
  { internalName = "dwcity:ThoriumBlock", displayName = "Ториевый блок", price = 6.00, currency = "res" },
  { internalName = "dwicty:Thorium_ingot", displayName = "Ториевый слиток", price = 0.67, currency = "res" },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор BH", price = 1.74, currency = "res", damage = 5 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор HH", price = 0.44, currency = "res", damage = 3 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор CH", price = 0.87, currency = "res", damage = 4 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор СВН", price = 6.87, currency = "res", damage = 6 },
  { internalName = "minecraft:pumpkin", displayName = "Тыква", price = 0.15, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "Тёмная осветительная панель", price = 0.26, currency = "res", damage = 200 },
  { internalName = "EndeIO:itemAlloy", displayName = "Тёмная сталь", price = 0.18, currency = "res", damage = 6 },
  { internalName = "dwcity:Dark_plate", displayName = "Тёмное покрытие", price = 4.05, price_ema = 0.5, currency = "res" },
  { internalName = "dwcity:Dark_dust", displayName = "Тёмный порошок", price = 0.22, currency = "res" },
  { internalName = "IC2:itemwcarbonrotor", displayName = "Углеволоконный ротор ветрогенератора", price = 10.08, currency = "res" },
  { internalName = "IC2:itemPartCarbonPlate", displayName = "Углепластик", price = 0.24, currency = "res" },
  { internalName = "IC2:itemPartCarbonMesh", displayName = "Углеткань", price = 0.24, currency = "res" },
  { internalName = "MineFactoryReloaded:machiner.0", displayName = "Удобритель", price = 2.47, currency = "res", damage = 4 },
  { internalName = "IC2:blockAlloyGlass", displayName = "Укреплённое стекло", price = 0.13, currency = "res" },
  { internalName = "IC2:blockAlloy", displayName = "Укреплённый камень", price = 0.25, currency = "res" },
  { internalName = "MineFactoryReloaded:upgrader.radius", displayName = "Улучшение (Медь)", price = 0.36, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Улучшение скорости для предметной трубы", price = 0.96, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Втягиватель", price = 1.15, currency = "res", damage = 6 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель", price = 1.15, currency = "res", damage = 3 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель жидкостей", price = 1.33, currency = "res", damage = 4 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Трансформатор", price = 1.28, currency = "res", damage = 1 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Ускоритель", price = 12.38, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Энергохранитель", price = 0.69, currency = "res", damage = 2 },
  { internalName = "luxinfineitems:AECompressedSpeedCard", displayName = "Улучшенная карта ускорения", price = 3.62, currency = "res" },
  { internalName = "luxinfineitems:advanced_portavle_storage_cell_0", displayName = "Улучшенная переносная ячейка", price = 14.51, currency = "res" },
  { internalName = "GraviSuite:advDDrill", displayName = "Улучшенный алмазный бур", price = 47.19, currency = "res" },
  { internalName = "GraviSuite:advLappack", displayName = "Улучшенный лаппак", price = 21.18, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Улучшенный молекулярный сборщик", price = 2.66, currency = "res" },
  { internalName = "GraviSuite:advNanoChestPlate", displayName = "Улучшенный наножилет", price = 68.71, currency = "res" },
  { internalName = "dwcity:Rare_plan", displayName = "Улучшенный чертёж", price = 4.48, currency = "res" },
  { internalName = "IC2:itemArmorLappack", displayName = "Ультимейт лаппак", price = 221.4, currency = "res" },
  { internalName = "IC2:itemFluidCell", displayName = "Универсальная жидкостная капсула", price = 0.2, currency = "res" },
  { internalName = "dwcity:Epic_plan", displayName = "Уникальный чертёж", price = 11.01, currency = "res" },
  { internalName = "GraviSuite:itemSimpleItem", displayName = "Ускоритель двигателя", price = 10.59, currency = "res", damage = 6 },
  { internalName = "appliedenergistics2:tile.BlockQuartzGrowthAccelerator", displayName = "Ускоритель роста кристаллов", price = 0.94, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Утилизатор", price = 1.59, currency = "res", damage = 11 },
  { internalName = "Genetics:misc", displayName = "Фермент", price = 0.25, currency = "res", damage = 3 },
  { internalName = "EnderIO:blockFarmStation", displayName = "Фермерская станция", price = 4.77, currency = "res" },
  { internalName = "DraconicEvolution:draconiumFluxCapacitor", displayName = "Флаксовый конденсатор Виверны", price = 1000.51, price_ema = 78, currency = "res" },
  { internalName = "dwcity:Flux_ingot", displayName = "Флаксовый слиток", price = 0.48, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Хранитель рамок улья", price = 8.6, currency = "res", damage = 1 },
  { internalName = "OpenComputers:item", displayName = "Центральный процессор (ЦП) (3-ий уровень)", price = 10.32, currency = "res", damage = 43 },
  { internalName = "Forestry:factory", displayName = "Центрифуга", price = 1.4, currency = "res", damage = 2 },
  { internalName = "IC2:itemFreq", displayName = "Частотный связыватель", price = 0.38, currency = "res" },
  { internalName = "minecraft:skull", displayName = "Череп скелета", price = 0.45, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Чистый изменчивый кристалл", price = 0.46, currency = "res", damage = 12 },
  { internalName = "MineFactoryReloaded:pinkslime", displayName = "Шарик розовой слизи", price = 0.25, price_ema = 0.2, currency = "res" },
  { internalName = "IC2:itemToolDrill", displayName = "Шахтёрский бур", price = 3.4, currency = "res" },
  { internalName = "Thaumcraft:ItemResource", displayName = "Шахтёрский лазер", price = 11.46, currency = "res" },
  { internalName = "minecraft:wool", displayName = "Шерсть", price = 0.1, currency = "res" },
  { internalName = "ThermalExpansion:material", displayName = "Шлак", price = 0.4, price_ema = 0.1, currency = "res", damage = 514 },
  { internalName = "DraconicEbolution:wyvernHelm", displayName = "Шлем Виверны", price = 560.91, price_ema = 16, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Экстрактор", price = 1.15, currency = "res", damage = 4 },
  { internalName = "Genetics:labMachine", displayName = "Экстрактор ДНК", price = 3.44, currency = "res", damage = 3 },
  { internalName = "IC2:blockKineticGenerator", displayName = "Электрический кинетический генератор", price = 2.41, currency = "res", damage = 2 },
  { internalName = "IC2:itemRecipePart", displayName = "Электромотор", price = 0.93, currency = "res", damage = 1 },
  { internalName = "IC2:blockMachine", displayName = "Электропечь", price = 0.88, currency = "res", damage = 2 },
  { internalName = "IC2:itemPartCircuit", displayName = "Электросхема", price = 0.34, currency = "res" },
  { internalName = "ExtraBeesalveary", displayName = "Электротрансформатор улья", price = 9.8, currency = "res", damage = 6 },
  { internalName = "ThermalFoundation:tool.hoeElectrum", displayName = "Электрумовый слиток", price = 0.16, currency = "res", damage = 71 },
  { internalName = "dwcity:Dark_element", displayName = "Элемент тьмы", price = 330.33, price_ema = 4, currency = "res" },
  { internalName = "dwcity:Ender_eye", displayName = "Эндер глаз", price = 13.94, currency = "res" },
  { internalName = "dwcity:Enderium_plate", displayName = "Эндериумная пластина", price = 0.89, currency = "res" },
  { internalName = "metadrive:neptunium_cindensator", displayName = "Эндериумный конденсатор", price = 2.9, currency = "res" },
  { internalName = "minecraft:end_stone", displayName = "Эндерняк", price = 0.11, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyCell", displayName = "Энергетическая ячейка", price = 0.67, currency = "res" },
  { internalName = "IC2:itemArmorEnergypack", displayName = "Энергетический ранец", price = 11.4, currency = "res" },
  { internalName = "EnderIO:itemAlloy", displayName = "Энергетический сплав", price = 0.4, currency = "res", damage = 1 },
  { internalName = "appliedenergistics2:tile.BlockQuartzLamp", displayName = "Энергичное кварцевое стекло", price = 0.55, currency = "res" },
  { internalName = "EnderIO:itemPowerConduitEndergy", displayName = "Энергопровод из кристаллического сплава 40960 RF/t", price = 0.38, currency = "res", damage = 8 },
  { internalName = "IC2:itemDust2", displayName = "Энергопыль", price = 0.23, currency = "res", damage = 2 },
  { internalName = "IC2:blockElectric", displayName = "Энергохранилище", price = 0.86, currency = "res" },
  { internalName = "IC2:blockGenerator", displayName = "Ядерный реактор", price = 40.13, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.ItemMultiMaterial", displayName = "Ядро истребления", price = 0.13, currency = "res", damage = 44 },
  { internalName = "minecraft:blaze_rod", displayName = "Стержень ифрита", price = 0.25, currency = "res" },
  { internalName = "minecraft:ender_pearl", displayName = "Жемчуг Эндера", price = 0.33, currency = "res" },
  { internalName = "minecraft:bone", displayName = "Кость", price = 0.5, currency = "res" },
  { internalName = "minecraft:slime_ball", displayName = "Сгусток слизи", price = 0.25, currency = "res" },
  { internalName = "Forestry:royalJelly", displayName = "Маточное молочко", price = 0.1, currency = "res" },
  { internalName = "AFSU:AFSU:0", displayName = "ЭХПФ", price = 500.29, price_ema = 23, currency = "res" },
  { internalName = "minecraft:stone", displayName = "Камень", price = 0.4, currency = "res" },
  { internalName = "minecraft:glass", displayName = "Стекло", price = 0.4, currency = "res" },
  { internalName = "minecraft:dispenser", displayName = "Раздатчик", price = 0.4, currency = "res" },
  { internalName = "minecraft:sticky_piston", displayName = "Липкий поршень", price = 0.15, currency = "res" },
  { internalName = "minecraft:web", displayName = "Паутина", price = 0.4, currency = "res" },
  { internalName = "minecraft:tnt", displayName = "Динамит", price = 0.25, currency = "res" },
  { internalName = "minecraft:cactus", displayName = "Кактус", price = 0.5, currency = "res" },
  { internalName = "minecraft:soul_sand", displayName = "Песок душ", price = 0.1, currency = "res" },
  { internalName = "minecraft:glowstone", displayName = "Светящийся камень", price = 0.25, currency = "res" },
  { internalName = "minecraft:enchanting_table", displayName = "Стол зачарований", price = 0.4, currency = "res" },
  { internalName = "minecraft:dragon_egg", displayName = "Яйцо дракона", price = 300, price_ema = 17, currency = "res" },
  { internalName = "minecraft:dropper", displayName = "Выбрасыватель", price = 0.4, currency = "res" },
  { internalName = "minecraft:book", displayName = "Книга", price = 0.4, currency = "res" },
  { internalName = "minecraft:fish", displayName = "Сырая треска", price = 0.4, currency = "res" },
  { internalName = "minecraft:magma_cream", displayName = "Сгусток магмы", price = 0.4, currency = "res" },
  { internalName = "minecraft:brewing_stand", displayName = "Варочная стойка", price = 0.4, currency = "res" },

}
