return {
  { internalName = "GraviSuite:vajra", displayName = "Ваджра", price = 275.36, currency = "res" },
  { internalName = "dwcity:Powder11", displayName = "Трижды сжатый камень", price = 11.00, currency = "res" },
  { internalName = "dwcity:Powder7", displayName = "Дважды сжатый адский кирпич", price = 555.55, currency = "res" },
  { internalName = "dwcity:PalladiumReactorChamber", displayName = "Палладиевая реакторная камера", price = 555.55, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ плотный кабель - Изменчивый", price = 0.82, currency = "res", damage = 76 },
  { internalName = "ae2stuff:Cable", displayName = "МЭ улучшенный кабель - Изменчивый", price = 2.82, currency = "res", damage = 16 },
  { internalName = "Forestry:craftingMaterial", displayName = "Пропитанная обшивка", price = 2.50, currency = "res", damage = 6 },
  { internalName = "Forestry:oakStick", displayName = "Полированная палка", price = 1.50, currency = "res" },
  { internalName = "metadrive:block_compressor", displayName = "Квантовый компрессор", price = 81.40, currency = "res" },
  { internalName = "metadrive:block_thermal_smelter", displayName = "Квантовая индукционная плавильня", price = 770.00, currency = "res" },
  { internalName = "metadrive:block_advanced_squeezer", displayName = "Квантовая соковыжималка", price = 91.90, currency = "res" },
  { internalName = "metadrive:block_ic2_centrifuge", displayName = "Квантовая термальная центрифуга", price = 91.90, currency = "res" },
  { internalName = "metadrive:block_advanced_carpenter", displayName = "Квантовый плотник", price = 91.90, currency = "res" },
  { internalName = "metadrive:block_extractor", displayName = "Квантовый экстрактор", price = 81.40, currency = "res" },
  { internalName = "metadrive:block_ore_washing", displayName = "Квантовый рудопромывочный механизм", price = 84.10, currency = "res" },
  { internalName = "metadrive:block_lava_generator", displayName = "Квантовый производитель лавы", price = 93.40, currency = "res" },
  { internalName = "metadrive:block_macverator", displayName = "Квантовый дробитель", price = 81.40, currency = "res" },
  { internalName = "metadrive:block_furnace", displayName = "Квантовая печь", price = 81.20, currency = "res" },
  { internalName = "metadrive:block_metal_former", displayName = "Квантовый металлоформовочный механизм", price = 82.88, currency = "res" },
  { internalName = "Forestry:propolis", displayName = "Прополис", price = 0.30, currency = "res" },
  { internalName = "minecraft:leather", displayName = "Кожа", price = 0.30, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockController", displayName = "МЭ контроллер", price = 2.30, currency = "res" },
  { internalName = "luxinfineitems:CompressedCPU", displayName = "Контроллер автокрафта", price = 375.21, currency = "res" },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 5.00, currency = "res", damage = 2 },
  { internalName = "EnderIO:itemLiquidConduit", displayName = "Жидкостная труба из мелодичного сплава", price = 5.00, currency = "res", damage = 5 },
  { internalName = "dwcity:Nano_seal2", displayName = "Тусклая нано-печать", price = 294.00, currency = "res" },
  { internalName = "dwcity:Dragon_seal2", displayName = "Тусклая печать дракона", price = 563.60, currency = "res" },
  { internalName = "dwcity:Lamp_seal2", displayName = "Тусклая печать света", price = 20.00, currency = "res" },
  { internalName = "dwcity:Bee_seal2", displayName = "Тусклая пчелиная печать", price = 110.00, currency = "res" },
  { internalName = "dwcity:Liquid_seal2", displayName = "Тусклая жидкостная печать", price = 20.00, currency = "res" },
  { internalName = "dwcity:Cube_seal2", displayName = "Тусклая кубическая печать", price = 70.00, currency = "res" },
  { internalName = "dwcity:Machine_seal2", displayName = "Тусклая механическая печать", price = 28.00, currency = "res" },
  { internalName = "dwcity:Optic_seal2", displayName = "Тусклая оптическая печать", price = 240.10, currency = "res" },
  { internalName = "dwcity:Chest_seal22", displayName = "Тусклая печать безопастности", price = 40.00, currency = "res" },
  { internalName = "dwcity:Food_seal2", displayName = "Тусклая печать голода", price = 15.00, currency = "res" },
  { internalName = "dwcity:Dnk_seal2", displayName = "Тусклая печать ДНК", price = 125.00, currency = "res" },
  { internalName = "dwcity:Sword_seal2", displayName = "Тусклая печать обороны", price = 20.00, currency = "res" },
  { internalName = "dwcity:Flower_seal2", displayName = "Тусклая печать розы", price = 10.00, currency = "res" },
  { internalName = "dwcity:Death_seal2", displayName = "Тусклая печать смерти", price = 62.00, currency = "res" },
  { internalName = "luxinfineitems:AdvancedEnergyCell", displayName = "Базовая энергетическая ячейка", price = 125.09, currency = "res", damage = 0 },
  { internalName = "EnderIO:itemPowerConduit", displayName = "Энергопровод из вибрирующего сплава ", price = 1.00, currency = "res", damage = 2 },
  { internalName = "metadrive:block_ic2_1_solar_panel", displayName = "Индустриальная солнечная панель II уровня", price = 25.00, currency = "res" },
  { internalName = "ic2:reactormoxquad", displayName = "Счетверённый топливный стержень (МОХ)", price = 60.00, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ жидкостный компонент хранилища", price = 261.91, currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "1024k МЭ компонент хранилища", price = 282.59, currency = "res", damage = 9 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "16K МЭ компонент хранения", price = 10.86, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.16k", displayName = "16K МЭ ячейка хранения", price = 11.64, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "16K хранилище создания", price = 12.168, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "16K МЭ жидкостный компонент хранилища", price = 9.405, currency = "res", damage = 6 },
  { internalName = "dwcity:Chip_16bit", displayName = "16-битный чип", price = 2.25, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "1K МЭ компонент хранения", price = 0.825, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.1k", displayName = "1K МЭ ячейка хранения", price = 1.61, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "1K хранилище создания", price = 2.208, currency = "res" },
  { internalName = "extracells:storage.component", displayName = "1K МЭ жидкостный компонент хранилища", price = 0.825, currency = "res", damage = 4 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ жидкостный компонент хранилища", price = 87.01, currency = "res", damage = 8 },
  { internalName = "extracells:storage.component", displayName = "256K МЭ компонент хранилища", price = 93.83, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "4K МЭ компонент хранения", price = 3.24, currency = "res", damage = 36 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.4k", displayName = "4K МЭ ячейка хранения", price = 4.02, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "4K хранилище создания", price = 4.548, currency = "res", damage = 1 },
  { internalName = "extracells:storage.component", displayName = "4K МЭ жидкостный компонент хранилища", price = 2.97, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "64K МЭ компонент хранения", price = 32.315, currency = "res", damage = 38 },
  { internalName = "appliedenergistics2:item.ItemBasicStorageCell.64k", displayName = "64K МЭ ячейка хранения", price = 34.5, currency = "res" },
  { internalName = "appliedenergistics2:item.tile.BlockCraftingStorage", displayName = "64K хранилище создания", price = 36.487, currency = "res", damage = 3 },
  { internalName = "extracells:storage.component", displayName = "64K МЭ жидкостный компонент хранилища", price = 28.71, currency = "res", damage = 7 },
  { internalName = "luxinfineitems:advancedCraftingStorage", displayName = "Хранилище создания МК1", price = 95.3, currency = "res" },
  { internalName = "luxinfineitems:advancedCraftingStorage", displayName = "Хранилище создания МК2", price = 285.11, currency = "res", damage = 1 },
  { internalName = "luxinfineitems:advancedCraftingAccelerator", displayName = "Блок обработки создания МК1", price = 7.54, currency = "res" },
  { internalName = "luxinfineitems:advancedCraftingAccelerator", displayName = "Блок обработки создания МК2", price = 28.41, currency = "res", damage = 1 },
  { internalName = "dwcity:Chip_64bit", displayName = "64-битный чип", price = 14.22, currency = "res" },
  { internalName = "mincraft:iron_ingot", displayName = "Железный слиток", price = 0.22, currency = "res", },
  { internalName = "EnderIO:blockSliceAndSplice", displayName = "Отрубатель и сращиватель", price = 4.73, currency = "res" },
  { internalName = "minecraft:nether_wart", displayName = "Адский нарост", price = 0.11, currency = "res" },
  { internalName = "dwcity:Akvamarin", displayName = "Аквамарин", price = 18.67, currency = "res" },
  { internalName = "Genetics:labMachine", displayName = "Акклиматизатор", price = 4.72, currency = "res" },
  { internalName = "IC2:itemArmorBatpack", displayName = "Аккумуляторный ранец", price = 2.47, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Алмазная электронная лампа", price = 0.57, currency = "res" },
  { internalName = "IC2:itemToolDDrill", displayName = "Алмазный бур", price = 8.58, currency = "res" },
  { internalName = "IronChest:BlockIronChest", displayName = "Алмазный сундук", price = 2.64, currency = "res" },
  { internalName = "IC2:itemCropnalyzer", displayName = "Анализатор агрокультур", price = 0.70, currency = "res" },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Армированная железная пластина", price = 8.8, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Базовая карта", price = 0.38, currency = "res", damage = 25 },
  { internalName = "dwcity:Basic_plan", displayName = "Базовый чертёж", price = 2.31, currency = "res" },
  { internalName = "BinnieCore:containerCylinder", displayName = "Баллон сырой ДНК", price = 2.75, currency = "res" },
  { internalName = "ae2wct:infinityBoosterCard", displayName = "Бесконечная карта усиления", price = 1489.37, currency = "res" },
  { internalName = "ectracells:terminal.fluid.wireless", displayName = "Беспроводной МЭ жидкостный терминал", price = 21.36, currency = "res" },
  { internalName = "extracells:terminal.universal.wireless", displayName = "Беспроводной МЭ универсальный терминал", price = 22.51, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Беспроводной приёмник", price = 3.32, currency = "res" },
  { internalName = "appliedenergistics2:item.ToolWirelessTeminal", displayName = "Беспроводной терминал", price = 21.25, currency = "res" },
  { internalName = "ae2wct:wirelessCraftingTerminal", displayName = "Беспроводной терминал создания", price = 483.92, currency = "res" },
  { internalName = "appliedenergistics2:item.ToolBiometricCard", displayName = "Биометрическая карта", price = 0.99, currency = "res" },
  { internalName = "IC2:blockMetal", displayName = "Блок закалённого железа", price = 1.98, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок обработки создания", price = 1.77, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingUnit", displayName = "Блок создания", price = 1.25, currency = "res" },
  { internalName = "ThermalExpansion:material", displayName = "Богатое удобрение", price = 0.11, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Ботинки Виверны", price = 485.16, currency = "res" },
  { internalName = "IC2:itemPlate", displayName = "Бронзовая пластина", price = 0.16, currency = "res", damage = 2 },
  { internalName = "IC2:itemIngot", displayName = "Бронзовый слиток", price = 0.15, currency = "res", damage = 2 },
  { internalName = "minecraft:cobblestone", displayName = "Булыжник", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый порошок", price = 0.22, currency = "res", damage = 1025 },
  { internalName = "ThermalFoundation:material", displayName = "Бурановый стержень", price = 0.44, currency = "res", damage = 1024 },
  { internalName = "minecraft:bucket", displayName = "Ведро", price = 0.33, currency = "res" },
  { internalName = "minecraft:crafting_table", displayName = "Верстак", price = 0.055, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCellWorkbench", displayName = "Верстак для ячеек", price = 0.715, currency = "res" },
  { internalName = "EnderIO:blockCapBank", displayName = "Вибрирующий блок конденсаторов", price = 21.68, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemMaterial", displayName = "Вибрирующий кристалл", price = 1.76, currency = "res", damage = 6 },
  { internalName = "EnderIO:itemAlloy", displayName = "Вибрирующий сплав", price = 0.862, currency = "res", damage = 2 },
  { internalName = "minecraft:hopper", displayName = "Воронка", price = 0.55, currency = "res" },
  { internalName = "ppliedenergistics2:tile.BlockInscriber", displayName = "Высекатель", price = 1.78, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Логический процессор", price = 0.17, currency = "res", damage = 22 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Вычислительный процессор", price = 0.17, currency = "res", damage = 23 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Инженерный процессор", price = 0.47, currency = "res", damage = 24 },
  { internalName = "IC2:blockGenerator", displayName = "Генератор", price = 1.078, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Генератор биотоплива", price = 2.64, currency = "res", damage = 11 },
  { internalName = "IC2:blockGenerator", displayName = "Геотермальный генератор", price = 1.254, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockEndermanSkull", displayName = "Голова стража Края", price = 2.2, currency = "res" },
  { internalName = "minecraft:gravel", displayName = "Гравий", price = 0.11, currency = "res" },
  { internalName = "minecraft:dirt", displayName = "Земля", price = 0.01, currency = "res" },
  { internalName = "DraconicEvolution:draconium", displayName = "Дракониевый блок", price = 28.78, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Дракониевый слиток", price = 3.92, currency = "res" },
  { internalName = "DraconicEvolution:draconicSword", displayName = "Драконий меч", price = 5285.34, currency = "res" },
  { internalName = "DraconicEvolution:draconicPickaxe", displayName = "Драконья кирка", price = 5735.99, currency = "res" },
  { internalName = "DraconicEvolution:draconicAxe", displayName = "Драконий топор", price = 5537.34, currency = "res" },
  { internalName = "DraconicEvolution:draconicShovel", displayName = "Драконья лопата", price = 5339.68, currency = "res" },
  { internalName = "DraconicEvolution:draconicBow", displayName = "Драконий лук", price = 5670.28, currency = "res" },
  { internalName = "DraconicEvolution:draconicHelm", displayName = "Драконий шлем", price = 5322.26, currency = "res" },
  { internalName = "DraconicEvolution:draconicChest", displayName = "Драконий нагрудник", price = 7268.83, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Драконьи поножи", price = 5359.67, currency = "res" },
  { internalName = "DraconicEvolution:wyvernBoots", displayName = "Драконьи ботинки", price = 5309.59, currency = "res" },
  { internalName = "DraconicEvolution:draconicStaffOfPower", displayName = "Драконий посох силы", price = 59923.00, currency = "res" },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Драконье ядро", price = 20.0, currency = "res" },
  { internalName = "dwcity:Granat", displayName = "Гранат", price = 5.5, currency = "res" },
  { internalName = "minecraft:red_mushroom", displayName = "Гриб", price = 0.38, currency = "res" },
  { internalName = "minecraft:gold_ingot", displayName = "Золотой слиток", price = 0.15, currency = "res" },
  { internalName = "Botany:pigment", displayName = "Зелёный краситель", price = 0.11, currency = "res", damage = 13 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал", price = 1.14, currency = "res", damage = 380 },
  { internalName = "appliedenergistics2:item.ItemBlockSecurity", displayName = "МЭ терминал безопасности", price = 13.67, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал интерфейсов", price = 1.98, currency = "res", damage = 480 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал создания", price = 1.32, currency = "res", damage = 360 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ терминал шаблонов", price = 1.86, currency = "res", damage = 340 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ умный кабель - Изменчивый", price = 0.31, currency = "res", damage = 56 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина импорта", price = 0.85, currency = "res", damage = 240 },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "МЭ шина экспорта", price = 0.78, currency = "res", damage = 260 },
  { internalName = "IC2:itemRecipePart", displayName = "Малый силовой агрегат", price = 2.13, currency = "res", damage = 3 },
  { internalName = "IC2:itemPlates", displayName = "Медная пластина", price = 0.11, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Медная электронная лампа", price = 0.65, currency = "res" },
  { internalName = "IC2:itemCable", displayName = "Медный провод", price = 0.05, currency = "res", damage = 1 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Мелодичный конденсатор", price = 25.79, currency = "res", damage = 4 },
  { internalName = "IC2:blockMachine2", displayName = "Металлоформовочный механизм", price = 2.97, currency = "res", damage = 4 },
  { internalName = "dwcity:Machine_seal2", displayName = "Механическая печать", price = 33.68, currency = "res" },
  { internalName = "DraconicEvolution:wyvernSword", displayName = "Меч Виверны", price = 498.65, currency = "res" },
  { internalName = "metadrive:module_fortune_luck_changer_tier_3", displayName = "Модуль удачи IV", price = 1265.0, currency = "res" },
  { internalName = "dwcity:Module_seal", displayName = "Модульная печать", price = 16.8, currency = "res" },
  { internalName = "metadrive:block_molecular_transfirmer", displayName = "Молекулярный преобразователь", price = 42.67, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockMolecularAssembler", displayName = "Молекулярный сборщик", price = 1.41, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockCraftingMonitor", displayName = "Монитор создания", price = 1.73, currency = "res" },
  { internalName = "minecraft:carrot", displayName = "Морковь", price = 0.02, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Мутатор улья", price = 22.5, currency = "res" },
  { internalName = "IC2NuclearControl:ItemMultipleSensorKit", displayName = "Набор для счётчика энергии", price = 1.43, currency = "res" },
  { internalName = "IC2NuclearControl:ItemEnergySensorKit", displayName = "Набор для энергетического хранилища", price = 1.65, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Навес улья", price = 22.75, currency = "res", damage = 2 },
  { internalName = "DraconicEvolution:wyvernChest", displayName = "Нагрудник Виверны", price = 624.88, currency = "res" },
  { internalName = "IC2:itemArmorNanoBoots", displayName = "Нано-ботинки", price = 6.74, currency = "res" },
  { internalName = "IC2:itemArmorNanoChestplate", displayName = "Нано-кираса", price = 8.63, currency = "res" },
  { internalName = "IC2:itemArmorLegas", displayName = "Нано-поножи", price = 7.62, currency = "res" },
  { internalName = "IC2:itemNanoSaber", displayName = "Нано-сабля", price = 7.94, currency = "res" },
  { internalName = "IC2:itemArmorNanoHelmet", displayName = "Нано-шлем", price = 16.49, currency = "res" },
  { internalName = "ThermalExpansion:Cell", displayName = "Наполнитель энергии", price = 64.21, currency = "res" },
  { internalName = "EnderIO:itemAlloy", displayName = "Наэлектризованная сталь", price = 0.23, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockSkyStone", displayName = "Небесный камень", price = 0.22, currency = "res" },
  { internalName = "IC2:itemBatREDischarged", displayName = "Незаряженный аккумулятор", price = 0.38, currency = "res" },
  { internalName = "dwcity:NeptuniumReactorChamber", displayName = "Нептуниевая реакторная камера", price = 493.92, currency = "res" },
  { internalName = "dwcity:AdvancedReactor", displayName = "Нептуниевый реактор", price = 1363.32, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Никелевый слиток", price = 0.12, currency = "res", damage = 68 },
  { internalName = "Forestry:alveary", displayName = "Обогреватель улья", price = 20.86, currency = "res", damage = 4 },
  { internalName = "minecraft:obsidian", displayName = "Обсидиан", price = 0.11, currency = "res" },
  { internalName = "IC2:itemPlates", displayName = "Обсидиановая пластина", price = 0.52, currency = "res", damage = 7 },
  { internalName = "IC2:itemDust", displayName = "Обсидиановая пыль", price = 0.11, currency = "res", damage = 11 },
  { internalName = "Forestry:thermionicTubes", displayName = "Обсидиановая электронная лампа", price = 0.42, currency = "res", damage = 6 },
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Объединитель солнечных панелей", price = 61.66, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Огненная электронная лампа", price = 0.65, currency = "res", damage = 7 },
  { internalName = "minecraft:ender_eye", displayName = "Око Эндера", price = 0.66, currency = "res" },
  { internalName = "ThermalFoundation:tool.fishingRodTin", displayName = "Оловянная пластина", price = 0.11, currency = "res", damage = 1 },
  { internalName = "Botany:insulatedTube", displayName = "Оловянная электронная лампа", price = 0.65, currency = "res", damage = 1 },
  { internalName = "dwcity:Optic_seal2", displayName = "Оптическая печать", price = 293.87, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Осветитель улья", price = 20.16, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemBasicCapacitor", displayName = "Основной конденсатор", price = 0.64, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Основной корпус механизма", price = 0.88, currency = "res" },
  { internalName = "EnderIO:itemBasicFilterUpgrade", displayName = "Основной предметный фильтр", price = 0.77, currency = "res" },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная лазуритовая пластина", price = 0.95, currency = "res", damage = 8 },
  { internalName = "IC2:itemDensePlates", displayName = "Плотная обсидиановая пластина", price = 0.95, currency = "res", damage = 7 },
  { internalName = "dwcity:Enderium_plate2", displayName = "Плотная эндериумная пластина", price = 8.96, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockDenseEnergyCell", displayName = "Плотная энергетическая ячейка", price = 16.88, currency = "res" },
  { internalName = "Forestry:factory", displayName = "Плотник", price = 1.56, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockPainter", displayName = "Покрасочный механизм", price = 2.53, currency = "res" },
  { internalName = "DraconicEvolution:wyvernLegs", displayName = "Поножи Виверны", price = 537.638, currency = "res" },
  { internalName = "minecraft:gunpowder", displayName = "Порох", price = 0.22, currency = "res" },
  { internalName = "minecraft:piston", displayName = "Поршень", price = 0.165, currency = "res" },
  { internalName = "EnderIO:itemTravelStaff", displayName = "Посох путешествия", price = 5.95, currency = "res" },
  { internalName = "EnderIO:itemConduit", displayName = "Предметная труба", price = 0.66, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyAcceptor", displayName = "Приёмщик энергии", price = 1.26, currency = "res" },
  { internalName = "DraconicEvolution:awakenedCore", displayName = "Пробуждённое ядро", price = 2516.24, currency = "res" },
  { internalName = "DraconicEvolution:draconiumIngot", displayName = "Пробуждённый дракониевый слиток", price = 44.13, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Продвинутая карта", price = 0.71, currency = "res", damage = 28 },
  { internalName = "Forestry:chipsets", displayName = "Продвинутая печатная плата", price = 0.66, currency = "res", damage = 1 },
  { internalName = "IC2:itemPartCircuiAdv", displayName = "Продвинутая электросхема", price = 0.96, currency = "res" },
  { internalName = "IC2:itemArmorAdvBatpack", displayName = "Продвинутый аккумуляторный ранец", price = 7.04, currency = "res" },
  { internalName = "ae2stuff:Inscriber", displayName = "Продвинутый высекатель", price = 76.21, currency = "res" },
  { internalName = "luxinfineitems:ExtendedPatternsEncoder", displayName = "Продвинутый кодировщик шаблонов", price = 420.0, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Продвинутый корпус механизма", price = 2.75, currency = "res", damage = 12 },
  { internalName = "metadrive:block_solar_panel_combiner", displayName = "Продвинутый объединитель солнечных панелей", price = 919.33, currency = "res", damage = 1 },
  { internalName = "MineFactoryReloaded:machine.1", displayName = "Производитель лавы", price = 3.63, currency = "res", damage = 5 },
  { internalName = "Forestry:frameImpregnated", displayName = "Пропитанная рамка", price = 1.77, currency = "res" },
  { internalName = "Forestry:thermionicTubes", displayName = "Прорезиненная электронная лампа", price = 0.01, currency = "res", damage = 8 },
  { internalName = "EnderIO:blockTransceiver", displayName = "Пространственный приёмопередатчик", price = 14.87, currency = "res" },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (1-ый уровень)", price = 3.52, currency = "res", damage = 8 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (2-ой уровень)", price = 4.62, currency = "res", damage = 9 },
  { internalName = "OpenComputers:item", displayName = "Видеокарта (3-ий уровень)", price = 7.15, currency = "res", damage = 10 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (2-ой уровень)", price = 23.95, currency = "res", damage = 102 },
  { internalName = "OpenComputers:item", displayName = "Процессор с видеокартой (APU) (Творческий)", price = 998.36, currency = "res", damage = 103 },
  { internalName = "EnderIO:itemAlloy", displayName = "Пульсирующее железо", price = 0.69, currency = "res", damage = 5 },
  { internalName = "minecraft:glass_bottle", displayName = "Пустая капсула", price = 0.33, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пустой шаблон", price = 1.35, currency = "res",  damage = 52 },
  { internalName = "dwcity:Bee_seal2", displayName = "Пчелиная печать", price = 199.2, currency = "res" },
  { internalName = "Forestry:beeswax", displayName = "Пчелиный воск", price = 0.55, currency = "res" },
  { internalName = "Forestry:alveary", displayName = "Пчелиный улей", price = 25.0, currency = "res" },
  { internalName = "minecraft:wheat", displayName = "Пшеница", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Пыль криотеума", price = 0.27, currency = "res", damage = 513 },
  { internalName = "ThermalFoundation:material", displayName = "Пыль пиротеума", price = 0.22, currency = "res", damage = 512 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Пыль небесного камня", price = 0.77, currency = "res",  damage = 45 },
  { internalName = "ThermalFoundation:material", displayName = "Пыль пиротеума", price = 0.22, currency = "res",  damage = 512 },
  { internalName = "IC2:reactorVentGold", displayName = "Разогнанный теплоотвод", price = 2.95, currency = "res" },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Основная)", price = 0.99, currency = "res" },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Резонирующая)", price = 7.28, currency = "res", damage = 3 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Укреплённая)", price = 3.13, currency = "res", damage = 2 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка механизма (Усиленная)", price = 2.07, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка свинцовой энергетической ячейки", price = 1.45, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Frame", displayName = "Рамка тессаракта (Полная)", price = 7.13, currency = "res", damage = 11 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная отдающая катушка", price = 0.77, currency = "res", damage = 80 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичная принимающая катушка", price = 0.85, currency = "res", damage = 128 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вторичное сито", price = 0.48, currency = "res", damage = 112 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Вулканический катализатор", price = 0.78, currency = "res", damage = 313 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная воронка", price = 0.39, currency = "res", damage = 1 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная красная схема", price = 0.99, currency = "res", damage = 32 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированная модульная структура", price = 0.54, currency = "res", damage = 16 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Интегрированный сервомеханизм", price = 0.39, currency = "res" },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Камера аннулирования", price = 0.88, currency = "res", damage = 144 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Канал отдающей катушки", price = 0.54, currency = "res", damage = 48 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ограничитель поля намагничивания", price = 0.64, currency = "res", damage = 49 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Оптимизация флаксовой связи", price = 0.99, currency = "res", damage = 65 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Отклик гиросервомеханизма", price = 1.23, currency = "res", damage = 114 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пирокластическое генерирование", price = 0.78, currency = "res", damage = 314 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Пространственно-временной унификатор", price = 2.24, currency = "res", damage = 130 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Разогнанный модульный редуктор", price = 1.21, currency = "res", damage = 129 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Регулятор криогенной катушки", price = 1.43, currency = "res", damage = 66 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Стабилизированная рамка", price = 0.56, currency = "res", damage = 113 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Тривекционная камера", price = 0.55, currency = "res", damage = 256 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Усилитель модуляции флакса", price = 0.99, currency = "res", damage = 81 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Ускоренная экструзия", price = 0.78, currency = "res", damage = 312 },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Фазовый резонатор", price = 708.48, currency = "res" },
  { internalName = "ThermalExpansion:augment", displayName = "Расширение: Флаксовый усилитель криогенной катушки", price = 1.43, currency = "res", damage = 82 },
  { internalName = "IC2:blockReactorChamber", displayName = "Реакторная камера", price = 11.73, currency = "res" },
  { internalName = "IC2:reactorPlating", displayName = "Реакторная обшивка", price = 0.63, currency = "res" },
  { internalName = "IC2:blockreactorvessel", displayName = "Реакторный корпус", price = 0.43, currency = "res" },
  { internalName = "IC2:blockReactorAccessHatch", displayName = "Реакторный люк", price = 1.1, currency = "res" },
  { internalName = "IC2:blockReactorFluidPort", displayName = "Реакторный насос", price = 1.32, currency = "res" },
  { internalName = "IC2:blockReactorRedstonePort", displayName = "Реакторный проводник красного сигнала", price = 1.55, currency = "res" },
  { internalName = "IC2:reactorVentCore", displayName = "Реакторный теплоотвод", price = 2.88, currency = "res" },
  { internalName = "EnderIO:blockReservoir", displayName = "Резервуар", price = 1.00, currency = "res" },
  { internalName = "IC2:itemRubber", displayName = "Резина", price = 0.03, currency = "res" },
  { internalName = "ThermalExpansion:Workbench", displayName = "Резонирующий вулканический пресс", price = 8.92, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Tank", displayName = "Резонирующий переносной бак", price = 96.86, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:Strongbox", displayName = "Резонирующий сейф", price = 5.29, currency = "res", damage = 4 },
  { internalName = "ThermalExpansion:capacitor", displayName = "Резонирующий флаксовый конденсатор", price = 4.6, currency = "res", damage = 5 },
  { internalName = "IC2:blockMachine2", displayName = "Рудопромывочный механизм", price = 4.24, currency = "res", damage = 5 },
  { internalName = "dwcity:Sostav", displayName = "Рыбий жир", price = 1.1, currency = "res" },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Рыболов", price = 3.15, currency = "res", damage = 1 },
  { internalName = "minecraft:lever", displayName = "Рычаг", price = 0.01, currency = "res" },
  { internalName = "MineFactoryReloaded:rubberwood.sapling", displayName = "Саженец гевеи", price = 0.11, currency = "res" },
  { internalName = "EnderIO:itemMaterial", displayName = "Самородок вибрирующего сплава", price = 0.99, currency = "res", damage = 4 },
  { internalName = "AdvancedSolarPanel:asp_crafting_items", displayName = "Саннариум", price = 13.5, currency = "res" },
  { internalName = "minecraft:sugar", displayName = "Сахар", price = 0.33, currency = "res" },
  { internalName = "minecraft:reeds", displayName = "Сахарный тростник", price = 0.22, currency = "res" },
  { internalName = "IC2:blockMachine3", displayName = "Сборщик урожая", price = 30.49, currency = "res", damage = 7 },
  { internalName = "IC2:itemPlates", displayName = "Свинцовая пластина", price = 0.11, currency = "res", damage = 6 },
  { internalName = "IC2:itemIngot", displayName = "Свинцовый слиток", price = 0.15, currency = "res", damage = 5 },
  { internalName = "EnderIO:itemMaterial", displayName = "Связующий элемент труб", price = 0.06, currency = "res", damage = 1 },
  { internalName = "EnderIO:blockSoulBinder", displayName = "Связыватель душ", price = 10.56, currency = "res" },
  { internalName = "minecraft:slime_ball", displayName = "Сгусток слизи", price = 0.65, currency = "res" },
  { internalName = "IC2:reactorUraniumDual", displayName = "Сдвоенный топливный стержень (Уран)", price = 3.63, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Селитра", price = 0.55, currency = "res", damage = 17 },
  { internalName = "minecraft:wheat_seeds", displayName = "Семена пшеницы", price = 0.01, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Сера", price = 0.55, currency = "res", damage = 16 },
  { internalName = "OpenComputers:item", displayName = "Сетевая карта", price = 0.671, currency = "res", damage = 11 },
  { internalName = "MineFactoryReloaded:machine.0", displayName = "Сеятель", price = 2.64, currency = "res" },
  { internalName = "IC2:itemRecipePart", displayName = "Силовой агрегат", price = 2.72, currency = "res", damage = 2 },
  { internalName = "PowerUtils:BlockMain", displayName = "Силовой конвертер", price = 14.45, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Синаловый слиток", price = 0.43, currency = "res", damage = 74 },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Сингулярность", price = 5.5, currency = "res", damage = 47 },
  { internalName = "Forestry:alveary", displayName = "Сито улья", price = 26.6, currency = "res", damage = 7 },
  { internalName = "IC2:blockMetal:3", displayName = "Слиток закалённого железа", price = 0.26, currency = "res", damage = 3 },
  { internalName = "IC2:itemIngot", displayName = "Слиток урана", price = 0.84, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Слиток эндериума", price = 1.00, currency = "res", damage = 76 },
  { internalName = "ThermalFoundation:material", displayName = "Смесь эндериума", price = 0.99, currency = "res", damage = 44 },
  { internalName = "minecraft:snowball", displayName = "Снежок", price = 0.01, currency = "res" },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Снижение скорости для предметной трубы", price = 1.62, currency = "res", damage = 1 },
  { internalName = "luxinfineitems:AECompressedSpeedCard", displayName = "Совершенная карта ускорения", price = 75.35, currency = "res", damage = 2 },
  { internalName = "luxinfineitems:advanced_portable_storage_cell_2", displayName = "Совершенная переносная ячейка", price = 440.0, currency = "res" },
  { internalName = "luxinfineitems:AEUltInterface", displayName = "Совершенный МЭ интерфейс", price = 18.62, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Совершенный молекулярный сборщик", price = 6.93, currency = "res", damage = 1 },
  { internalName = "OpenConputers:item", displayName = "Соединённая карта", price = 10.33, currency = "res", damage = 51 },
  { internalName = "Forestry:factory", displayName = "Соковыжималка", price = 1.63, currency = "res", damage = 5 },
  { internalName = "IC2:blockGenerator", displayName = "Солнечная панель", price = 2.79, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine3", displayName = "Солнечный опреснитель", price = 1.32, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemAlloy", displayName = "Сплав из красного камня", price = 0.06, currency = "res", damage = 3 },
  { internalName = "IC2:blockMachine2", displayName = "Термальная центрифуга", price = 12.42, currency = "res", damage = 3 },
  { internalName = "dwcity:Topaz", displayName = "Топаз", price = 0.55, currency = "res" },
  { internalName = "IC2:itemTritiumCell", displayName = "Топливный стержень (Тритий)", price = 48.0, currency = "res" },
  { internalName = "IC2:reactoryUraniumSimple", displayName = "Топливный стержень (Уран)", price = 1.76, currency = "res" },
  { internalName = "IC2:blockPersonal", displayName = "Торговый аппарат", price = 33.37, currency = "res", damage = 1 },
  { internalName = "dwcity:ThoriumBlock", displayName = "Ториевый блок", price = 7.95, currency = "res" },
  { internalName = "dwicty:Thorium_ingot", displayName = "Ториевый слиток", price = 0.78, currency = "res" },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор BH", price = 2.11, currency = "res", damage = 5 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор HH", price = 0.44, currency = "res", damage = 3 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор CH", price = 5.24, currency = "res", damage = 4 },
  { internalName = "IC2:blockElectric", displayName = "Трансформатор СВН", price = 0.96, currency = "res", damage = 6 },
  { internalName = "minecraft:pumpkin", displayName = "Тыква", price = 0.11, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiPart", displayName = "Тёмная осветительная панель", price = 0.24, currency = "res", damage = 200 },
  { internalName = "EndeIO:itemAlloy", displayName = "Тёмная сталь", price = 0.23, currency = "res", damage = 6 },
  { internalName = "dwcity:Dark_plate", displayName = "Тёмное покрытие", price = 7.56, currency = "res" },
  { internalName = "dwcity:Dark_dust", displayName = "Тёмный порошок", price = 0.22, currency = "res" },
  { internalName = "IC2:itemwcarbonrotor", displayName = "Углеволоконный ротор ветрогенератора", price = 17.82, currency = "res" },
  { internalName = "IC2:itemPartCarbonPlate", displayName = "Углепластик", price = 0.46, currency = "res" },
  { internalName = "IC2:itemPartCarbonMesh", displayName = "Углеткань", price = 0.44, currency = "res" },
  { internalName = "MineFactoryReloaded:machiner.0", displayName = "Удобритель", price = 2.87, currency = "res", damage = 4 },
  { internalName = "IC2:blockAlloyGlass", displayName = "Укреплённое стекло", price = 0.43, currency = "res" },
  { internalName = "IC2:blockAlloy", displayName = "Укреплённый камень", price = 0.55, currency = "res" },
  { internalName = "MineFactoryReloaded:upgrader.radius", displayName = "Улучшение (Медь)", price = 0.45, currency = "res", damage = 3 },
  { internalName = "EnderIO:itemExtractSpeedUpgrade", displayName = "Улучшение скорости для предметной трубы", price = 1.32, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Втягиватель", price = 1.36, currency = "res", damage = 6 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель", price = 1.36, currency = "res", damage = 3 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Выталкиватель жидкостей", price = 1.48, currency = "res", damage = 4 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Инвертор сигнала красного камня", price = 0.44, currency = "res", damage = 5 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Трансформатор", price = 1.43, currency = "res", damage = 1 },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Ускоритель", price = 16.77, currency = "res" },
  { internalName = "IC2:upgradeModule", displayName = "Улучшение: Энергохранитель", price = 0.88, currency = "res", damage = 2 },
  { internalName = "luxinfineitems:AECompressedSpeedCard", displayName = "Улучшенная карта ускорения", price = 4.22, currency = "res" },
  { internalName = "luxinfineitems:advanced_portavle_storage_cell_0", displayName = "Улучшенная переносная ячейка", price = 24.35, currency = "res" },
  { internalName = "luxinfineitems:AEAdvInterface", displayName = "Улучшенный МЭ интерфейс", price = 2.56, currency = "res" },
  { internalName = "GraviSuite:advDDrill", displayName = "Улучшенный алмазный бур", price = 47.37, currency = "res" },
  { internalName = "GraviSuite:advLappack", displayName = "Улучшенный лаппак", price = 24.104, currency = "res" },
  { internalName = "luxinfineitems:AEAdvMolecularAssembler", displayName = "Улучшенный молекулярный сборщик", price = 3.46, currency = "res" },
  { internalName = "luxinfineitems:advancedDrive", displayName = "Улучшенный МЭ накопитель", price = 6.98, currency = "res" },
  { internalName = "GraviSuite:advNanoChestPlate", displayName = "Улучшенный наножилет", price = 73.77, currency = "res" },
  { internalName = "dwcity:Rare_plan", displayName = "Улучшенный чертёж", price = 5.72, currency = "res" },
  { internalName = "IC2:itemArmorLappack", displayName = "Ультимейт лаппак", price = 160.05, currency = "res" },
  { internalName = "IC2:itemFluidCell", displayName = "Универсальная жидкостная капсула", price = 0.22, currency = "res" },
  { internalName = "dwcity:Epic_plan", displayName = "Уникальный чертёж", price = 10.45, currency = "res" },
  { internalName = "IC2:itemUran238", displayName = "Уран-238", price = 0.135, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Усилитель беспроводного сигнала", price = 1.85, currency = "res", damage = 42 },
  { internalName = "GraviSuite:itemSimpleItem", displayName = "Ускоритель двигателя", price = 10.69, currency = "res", damage = 6 },
  { internalName = "appliedenergistics2:tile.BlockQuartzGrowthAccelerator", displayName = "Ускоритель роста кристаллов", price = 2.44, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Утилизатор", price = 1.68, currency = "res", damage = 11 },
  { internalName = "Genetics:misc", displayName = "Фермент", price = 0.65, currency = "res", damage = 3 },
  { internalName = "EnderIO:blockFarmStation", displayName = "Фермерская станция", price = 6.63, currency = "res" },
  { internalName = "dwcity:Flux_plate", displayName = "Флаксовая пластина", price = 0.99, currency = "res" },
  { internalName = "DraconicEvolution:draconiumFluxCapacitor", displayName = "Флаксовый конденсатор Виверны", price = 1011.3, currency = "res" },
  { internalName = "dwcity:Flux_ingot", displayName = "Флаксовый слиток", price = 1.35, currency = "res" },
  { internalName = "IC2:itemHops", displayName = "Хмель", price = 0.21, currency = "res" },
  { internalName = "ExtraBees:alveary", displayName = "Хранитель рамок улья", price = 21.5, currency = "res", damage = 1 },
  { internalName = "OpenComputers:item", displayName = "Центральный процессор (ЦП) (3-ий уровень)", price = 12.88, currency = "res", damage = 43 },
  { internalName = "Forestry:factory", displayName = "Центрифуга", price = 1.63, currency = "res", damage = 2 },
  { internalName = "IC2:itemFreq", displayName = "Частотный связыватель", price = 0.45, currency = "res" },
  { internalName = "minecraft:skull", displayName = "Череп скелета", price = 1.98, currency = "res" },
  { internalName = "appliedenergistics2:item.ItemMultiMaterial", displayName = "Чистый изменчивый кристалл", price = 0.19, currency = "res", damage = 12 },
  { internalName = "MineFactoryReloaded:pinkslime", displayName = "Шарик розовой слизи", price = 1.87, currency = "res" },
  { internalName = "IC2:itemToolDrill", displayName = "Шахтёрский бур", price = 3.68, currency = "res" },
  { internalName = "Thaumcraft:ItemResource", displayName = "Шахтёрский лазер", price = 7.56, currency = "res" },
  { internalName = "minecraft:wool", displayName = "Шерсть", price = 0.11, currency = "res" },
  { internalName = "ThermalFoundation:material", displayName = "Шестерня из эндериума", price = 4.07, currency = "res", damage = 140 },
  { internalName = "ThermalExpansion:material", displayName = "Шлак", price = 0.11, currency = "res", damage = 514 },
  { internalName = "DraconicEbolution:wyvernHelm", displayName = "Шлем Виверны", price = 539.45, currency = "res" },
  { internalName = "IC2:blockMachine", displayName = "Экстрактор", price = 1.98, currency = "res", damage = 4 },
  { internalName = "Genetics:labMachine", displayName = "Экстрактор ДНК", price = 4.59, currency = "res", damage = 3 },
  { internalName = "IC2:blockKineticGenerator", displayName = "Электрический кинетический генератор", price = 2.65, currency = "res", damage = 2 },
  { internalName = "IC2:itemRecipePart", displayName = "Электромотор", price = 0.98, currency = "res", damage = 1 },
  { internalName = "IC2:blockMachine", displayName = "Электропечь", price = 1.78, currency = "res", damage = 2 },
  { internalName = "IC2:itemPartCircuit", displayName = "Электросхема", price = 0.47, currency = "res" },
  { internalName = "ExtraBeesalveary", displayName = "Электротрансформатор улья", price = 24.0, currency = "res", damage = 6 },
  { internalName = "ThermalFoundation:tool.hoeElectrum", displayName = "Электрумовый слиток", price = 0.11, currency = "res", damage = 71 },
  { internalName = "dwcity:Dark_element", displayName = "Элемент тьмы", price = 394.84, currency = "res" },
  { internalName = "dwcity:Ender_eye", displayName = "Эндер глаз", price = 21.87, currency = "res" },
  { internalName = "dwcity:Enderium_plate", displayName = "Эндериумная пластина", price = 0.99, currency = "res" },
  { internalName = "metadrive:neptunium_cindensator", displayName = "Эндериумный конденсатор", price = 298.78, currency = "res" },
  { internalName = "dwcity:Scattering_crystal", displayName = "Эндериумный хладагент", price = 3.35, currency = "res" },
  { internalName = "minecraft:end_stone", displayName = "Эндерняк", price = 0.11, currency = "res" },
  { internalName = "appliedenergistics2:tile.BlockEnergyCell", displayName = "Энергетическая ячейка", price = 2.85, currency = "res" },
  { internalName = "IC2:itemArmorEnergypack", displayName = "Энергетический ранец", price = 13.93, currency = "res" },
  { internalName = "EnderIO:itemAlloy", displayName = "Энергетический сплав", price = 0.88, currency = "res", damage = 1 },
  { internalName = "appliedenergistics2:tile.BlockQuartzLamp", displayName = "Энергичное кварцевое стекло", price = 0.45, currency = "res" },
  { internalName = "EnderIO:itemPowerConduitEndergy", displayName = "Энергопровод из кристаллического сплава 40960 RF/t", price = 1.65, currency = "res", damage = 8 },
  { internalName = "IC2:itemDust2", displayName = "Энергопыль", price = 0.231, currency = "res", damage = 2 },
  { internalName = "IC2:blockElectric", displayName = "Энергохранилище", price = 1.22, currency = "res" },
  { internalName = "IC2:blockGenerator", displayName = "Ядерный реактор", price = 41.69, currency = "res", damage = 5 },
  { internalName = "appliedenergistics2:tile.ItemMultiMaterial", displayName = "Ядро истребления", price = 0.32, currency = "res", damage = 44 },
  { internalName = "minecraft:blaze_rod", displayName = "Стержень ифрита", price = 0.60, currency = "res" },
  { internalName = "minecraft:ender_pearl", displayName = "Жемчуг Эндера", price = 0.75, currency = "res" },
  { internalName = "minecraft:bone", displayName = "Кость", price = 0.30, currency = "res" },
  { internalName = "minecraft:slime_ball", displayName = "Сгусток слизи", price = 0.65, currency = "res" },
  { internalName = "Forestry:royalJelly", displayName = "Маточное молочко", price = 0.80, currency = "res" },
  { internalName = "AFSU:AFSU:0", displayName = "AFSU", price = 1.0, currency = "res" },
  { internalName = "DraconicEvolution:draconicCore", displayName = "Awakened Core", price = 20.0, currency = "res" },
  { internalName = "IC2:itemPlutonium", displayName = "Плутоний", price = 4.90, currency = "res" },
  { internalName = "minecraft:stone", displayName = "Камень", price = 0.02, currency = "res" },
  { internalName = "dwcity:Powder11", displayName = "Трижды сжатый камень", price = 15.00, currency = "res" }

}
